if(EXISTS "D:/LearnSomething/LearnCmake/lab2/build_static/tests/test_string[1]_tests.cmake")
  include("D:/LearnSomething/LearnCmake/lab2/build_static/tests/test_string[1]_tests.cmake")
else()
  add_test(test_string_NOT_BUILT test_string_NOT_BUILT)
endif()
